# Generated by Django 4.2.1 on 2024-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
    ]
