# Generated by Django 4.2.1 on 2024-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_customuser_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signature',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
