# Generated by Django 4.2.1 on 2024-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_customuser_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salt',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='signature',
            field=models.CharField(max_length=128),
        ),
    ]
